---

configure_osx: true

configure_dotfiles: true
dotfiles_repo_local_destination: ~/development/private/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore_global
  - .osx
  - .zshrc
  - .bin/idea
dotfiles_gitconfig_email: patryk.semen@gmail.com


configure_sublime: false
configure_terminal: false
configure_sudoers: false

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - App Store
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - FaceTime
  - iTunes
  - iBooks
  - Siri
  - Safari
  - Messages
  - Calendar
  - Music
  - Keynote
  - Numbers
  - Pages
  - System Preferences
  - Downloads
  - Docker Desktop
dockitems_persist:
 - name: "Google Chrome"
   path: "/Applications/Google Chrome.app/"
   pos: 1
 - name: "IntelliJ IDEA"
   path: "/Applications/IntelliJ IDEA.app/"
   pos: 2
 - name: "Slack"
   path: "/Applications/Slack.app/"
   pos: 3
 - name: "Spotify"
   path: "/Applications/Spotify.app/"
   pos: 4
 - name: "OpenLens"
   path: "/Applications/OpenLens.app/"
   pos: 5
 - name: "Mail"
   path: "/Applications/Mail.app/"
   pos: 6
 - name: "Warp"
   path: "/Applications/Warp.app/"
   pos: 7

homebrew_installed_packages:
  - awscli
  - aws-shell
  - curl
  - nmap
  - docker
  - docker-compose
  - helm
  - kubernetes-cli
  - steampipe
  - datawire/blackbird/telepresence-arm64
  - telnet
  - terraform
  - terragrunt
  - git
  - htop
  - jq
  - maven
  - node
  - python
  - tree
  - wget
  - watch
  - zsh
  - k9s
  - gh
  - rustup
  - stern

homebrew_cask_apps:
  - docker
  - warp
  - intellij-idea
  - slack
  - spotify
#  - openlens #FIXME currently doesn't work on 6.3.0 and there is no simple way to downgrade in homebrew
  - temurin
  - karabiner-elements

configure_dev_env: true