---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
        - "{{ playbook_dir }}/overrides/*.yml"
      tags: ['always']
    - name: Create ~/.bin Directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.bin"
    - name: Create ~/.config/karabiner Directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.config/karabiner"
    - import_tasks: tasks/render-dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text']

    - import_tasks: tasks/dev-env.yml
      when: configure_dev_env
      tags: ['dev-env']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"

# Currently manual steps are:
# installing xcode
# installing ansible
# approving all kind of access for apps
# disabling emoji and "open man page" shortcuts
# toggle function keys behind Fn
#   https://apple.stackexchange.com/questions/422371/how-to-disable-cmdshifta-and-cmdshiftm-from-cli-in-macos / https://gist.github.com/rngtng/652031/fcc19fb55d1dec96acf3e4683091e57c676abc7f
#   https://appsliced.co/ask/how-do-i-disable-the-emoji-keyboard-shortcut-on-my-mac√
# disabling notifications & sound in Mail app
# change desktop background to black on all displays/desktops
# install openlens extension https://github.com/alebcay/openlens-node-pod-menu
# idea configuration sync + plugins install
# warp settings sync