---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
        - "{{ playbook_dir }}/overrides/*.yml"
      tags: ['always']
    - name: Create ~/.bin Directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.bin"
    - import_tasks: tasks/render-dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text']

    - import_tasks: tasks/dev-env.yml
      when: configure_dev_env
      tags: ['dev-env']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"

#TODO displays orientation, placement, wide as main
#TODO warp config
#TODO remove % on the end of command output
#TODO review https://github.com/pivovarit/mac-os-playbook/blob/c689e4cfe0ab67351592d845a1158c4b26aa9a68/roles/macos-config/tasks/main.yml
#TODO review https://github.com/pivovarit/mac-os-playbook/blob/c689e4cfe0ab67351592d845a1158c4b26aa9a68/roles/macos-config/tasks/finder-config.yml
#TODO review https://github.com/pivovarit/mac-os-playbook/blob/c689e4cfe0ab67351592d845a1158c4b26aa9a68/roles/macos-config/tasks/dock-config.yml
#TODO customize macos shortcuts
#TODO review https://github.com/pivovarit/mac-os-playbook/blob/c689e4cfe0ab67351592d845a1158c4b26aa9a68/group_vars/all
#TODO review https://github.com/geerlingguy/dotfiles
#TODO aliases for docker run & docker build, enter running container
#TODO alias for replace in file
#TODO aliases for kubectl common cases
#TODO set git private mail for dotfiles & mac-dev-playbook
#TODO some solution for deep work (exit from slack, mail and restore after x?)
#TODO cli dictionary
#TODO cli calculator
#TODO httpie
#TODO lower, other text manipulation commands command
#TODO sleep on closing macbook
#TODO window alignment
#TODO separate windows of applications
#TODO tray system monitor (cpu/mem/network usage)
#TODO automate rustup-init -y cat .zshenv #. "$HOME/.cargo/env"
#TODO karabiner dotfiles; karabiner autostart in tray; https://ke-complex-modifications.pqrs.org/#device-specific
#TODO disable shortcuts
#  https://apple.stackexchange.com/questions/422371/how-to-disable-cmdshifta-and-cmdshiftm-from-cli-in-macos / https://gist.github.com/rngtng/652031/fcc19fb55d1dec96acf3e4683091e57c676abc7f
#  https://appsliced.co/ask/how-do-i-disable-the-emoji-keyboard-shortcut-on-my-mac√