---

- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Render all templates
  template:
    src: '{{ item.src }}'
    dest: '{{ dotfiles_repo_local_destination }}/{{ item.path }}'
    force: yes
  with_filetree: '{{ dotfiles_repo_local_destination }}/templates/'
  when: item.state == 'file'